name: "ecommerce_dbt"
version: "1.0.0"
profile: "ecommerce_mysql"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

models:
  ecommerce_dbt:
    staging:
      +materialized: view
      +schema: "staging"
    marts:
      +materialized: table
      +schema: "marts"
