version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_users
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: stg_order_lines
    columns:
      - name: order_id
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
